const data = {
  products: [
    {
      name: 'Camisa Nike',
      slug: 'camisa-nike',
      category: 'Camisetas',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      rumReviews: 10,
      description: 'Camisa Alta Calidad',
    },
    {
      name: 'Camisa Adidas',
      slug: 'camisa-Adidas',
      category: 'Camisetas',
      image: '/images/p2.jpg',
      price: 120,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      rumReviews: 10,
      description: 'Camisa Adidas Alta Calidad',
    },
    {
      name: 'Pantalon Nike',
      slug: 'Pantalon-nike',
      category: 'Pantalones',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      rumReviews: 14,
      description: 'Pantalon Alta Calidad',
    },
    {
      name: 'Pantalon Adidas',
      slug: 'Pantalon-Adidas',
      category: 'Pantalones',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      rumReviews: 10,
      description: 'Pantalon Adidas Alta Calidad',
    },
  ],
};
export default data;
